name: API CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  api-testing:
    # chay ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      # Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Bạn có thể dùng 18, 20, v.v.

      # Newman
      # Cài đặt Newman trên máy ảo
      - name: Install Newman
        run: npm install -g newman

      #  Chạy Postman tests
      - name: Run API Tests with Newman
        run: newman run postman/API-Testing-Demo.postman_collection.json
